import os
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from datetime import datetime
from app.core.config import settings

class XLSXGenerator:
    def generate_sensor_analytics_sheet(self, data_file: str = None) -> str:
        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = "P-102B Telemetry & Anomaly Log"
        
        # Styles
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="0B3C5D", end_color="0B3C5D", fill_type="solid")
        title_font = Font(name="Calibri", size=16, bold=True, color="0B3C5D")
        
        # Title Block
        ws["A1"] = "MRPL CENTRIFUGAL PUMP P-102B TELEMETRY & ANOMALY ANALYSIS"
        ws["A1"].font = title_font
        ws["A2"] = f"Generated by SOVEREIGN-X Sandboxed Python Engine on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
        
        # Headers
        headers = ["Timestamp", "Vibration (mm/s)", "Bearing Temp (°C)", "Discharge Pressure (bar)", "Flow Rate (m3/h)", "ISO 10816 Status"]
        for col_idx, h in enumerate(headers, 1):
            cell = ws.cell(row=4, column=col_idx, value=h)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")
            
        # Sample Telemetry Data Rows
        sample_rows = [
            ["2026-08-28 08:00", 3.2, 65.4, 12.1, 450.0, "NORMAL"],
            ["2026-08-28 09:00", 3.4, 66.8, 12.0, 451.2, "NORMAL"],
            ["2026-08-28 10:00", 4.1, 71.2, 11.9, 448.5, "WARNING"],
            ["2026-08-28 11:00", 4.8, 77.5, 11.8, 445.0, "EXCEEDED"],
            ["2026-08-28 12:00", 5.6, 82.1, 11.5, 440.0, "EXCEEDED"],
            ["2026-08-28 13:00", 6.8, 88.3, 11.2, 432.0, "CRITICAL SHUTDOWN"]
        ]
        
        for row_idx, r in enumerate(sample_rows, 5):
            for col_idx, val in enumerate(r, 1):
                cell = ws.cell(row=row_idx, column=col_idx, value=val)
                if col_idx == 6:
                    if "CRITICAL" in str(val) or "EXCEEDED" in str(val):
                        cell.fill = PatternFill(start_color="FFD2D2", end_color="FFD2D2", fill_type="solid")
                        cell.font = Font(color="9C0006", bold=True)
                    else:
                        cell.fill = PatternFill(start_color="D4EDDA", end_color="D4EDDA", fill_type="solid")
                        cell.font = Font(color="155724", bold=True)
                        
        filename = f"P102B_Sensor_Analytics_{int(datetime.now().timestamp())}.xlsx"
        file_path = os.path.join(settings.DELIVERABLES_DIR, filename)
        wb.save(file_path)
        return file_path

xlsx_generator = XLSXGenerator()
